# fly.toml app configuration file generated for credit-scoring on 2023-08-03T11:29:15-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "credit-scoring"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 8002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
