{
 "title": "ScoreCard Monitoring",
 "time": { "from": "2023-02-01T00:00:00.000Z", "to": "2023-02-12T00:00:00.000Z" },
 "panels": [
  {
   "title": "Number of Missing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM risk_score_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM risk_score_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Predicted Dalily drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM risk_score_metrics LIMIT 50 "
    }
   ]
  }
 ]
}