col_map = {
    'riskperformance': 'RiskPerformance',
    'externalriskestimate': 'ExternalRiskEstimate',
    'msinceoldesttradeopen': 'MSinceOldestTradeOpen',
    'msincemostrecenttradeopen': 'MSinceMostRecentTradeOpen',
    'averageminfile': 'AverageMInFile',
    'numsatisfactorytrades': 'NumSatisfactoryTrades',
    'numtrades60ever2derogpubrec': 'NumTrades60Ever2DerogPubRec',
    'numtrades90ever2derogpubrec': 'NumTrades90Ever2DerogPubRec',
    'percenttradesneverdelq': 'PercentTradesNeverDelq',
    'msincemostrecentdelq': 'MSinceMostRecentDelq',
    'maxdelq2publicreclast12m': 'MaxDelq2PublicRecLast12M',
    'maxdelqever': 'MaxDelqEver',
    'numtotaltrades': 'NumTotalTrades',
    'numtradesopeninlast12m': 'NumTradesOpeninLast12M',
    'percentinstalltrades': 'PercentInstallTrades',
    'msincemostrecentinqexcl7days': 'MSinceMostRecentInqexcl7days',
    'numinqlast6m': 'NumInqLast6M',
    'numinqlast6mexcl7days': 'NumInqLast6Mexcl7days',
    'netfractionrevolvingburden': 'NetFractionRevolvingBurden',
    'netfractioninstallburden': 'NetFractionInstallBurden',
    'numrevolvingtradeswbalance': 'NumRevolvingTradesWBalance',
    'numinstalltradeswbalance': 'NumInstallTradesWBalance',
    'numbank2natltradeswhighutilization': 'NumBank2NatlTradesWHighUtilization',
    'percenttradeswbalance': 'PercentTradesWBalance',
}
